export const WEDDING_DATA = {
  groom: "Dr. Piyush",
  bride: "Dr. Shini",
  introMessage: "We are honored to welcome you to the\nWedding ceremony of our beloved son",
  togetherText: "Together with our families & friends",
  requestText: "REQUEST THE HONOUR OF YOUR PRESENCE",
  datesSummary: "01 · 04 DECEMBER 2026 • ORCHHA, MP",
  familyNameSummary: "Dr. Usha, Dr. Dinesh & Kaushik Family",
  weddingDateFormatted: "1 DECEMBER 2026",
  weddingDayOfWeek: "TUESDAY",
  weddingTimeFormatted: "AT 5:00 PM",
  targetTimestamp: new Date("2026-12-01T17:00:00+05:30").getTime(),
  venueName1: "Pooja Hospital",
  venueAddress1: "Narnaul, Haryana",
  googleMapsUrl1: "https://maps.app.goo.gl/zGerQX6HYPra1P3HA",
  venueName2: "Raj Vilas",
  venueAddress2: "Orchha, Madhya Pradesh",
  googleMapsUrl2: "https://maps.app.goo.gl/SjAinaMEUt6Tcjgt7?g_st=ic",
  welcomeMessage:
    "“With hearts full of joy, we warmly invite you to celebrate the wedding of our beloved son.\n\n Your presence and blessings will make this joyous occasion truly special.”",
  whatsappNumber: "+91 82969 52770",
  whatsappRawNumber: "918296952770",
  events: [
    {
      date: "Tuesday, 01 December 2026",
      title: "Lagan Ceremony",
      desc: "An auspicious start with beautiful henna patterns, folk music, and joyful celebrations.",
    },
    {
      date: "Friday, 04 December 2026",
      title: "Wedding Ceremony",
      desc: "A vibrant celebration of sacred turmeric blessings, family love, and laughter.",
    },
  ],
};

export const SCRATCH_PALETTE = {
  gradStart: "#fde2e8",
  gradMid: "#c97a8c",
  gradEnd: "#4a1525",
  speckLightRgb: "253, 226, 232",
  speckMidRgb: "201, 122, 140",
  speckDarkRgb: "74, 21, 37",
  sparkleRgb: "255, 240, 245",
  revealBg: "#ffffff",
  heartBorder: "#8b233a",
  titleColor: "#8b233a",
  dateColor: "#2b141b",
  dayColor: "#8b233a",
  timeColor: "#45202a",
};
